# Generated by Django 5.1 on 2026-08-19 14:52

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'breeds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PuppyFarm', max_length=100)),
                ('tagline', models.CharField(default='Find Your Perfect Pup', max_length=255)),
                ('admin_whatsapp', models.CharField(help_text='Country code + number, no + or spaces. e.g., 919876543210', max_length=20)),
                ('admin_phone', models.CharField(help_text='Display format. e.g., +91 98765 43210', max_length=20)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('hero_title', models.CharField(default='Find Your Perfect Pup 🐶', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, default='Healthy, vaccinated puppies from trusted breeders', max_length=500)),
                ('popup_enabled', models.BooleanField(default=True)),
                ('popup_title', models.CharField(default='Hellow hooman! 🐶', max_length=100)),
                ('popup_message', models.CharField(default='Looking for a furry friend? Chat with us now!', max_length=255)),
                ('popup_delay_seconds', models.PositiveIntegerField(default=5, help_text='Seconds before pop-up appears')),
                ('total_happy_families', models.PositiveIntegerField(default=100)),
                ('years_in_business', models.PositiveIntegerField(default=5)),
                ('total_breeds_available', models.PositiveIntegerField(default=20)),
                ('auto_delete_sold_days', models.PositiveIntegerField(default=3, help_text='Days after marking sold before auto-deleting dog and photos')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('about_us', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'db_table': 'site_config',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Optional photo of customer with their dog', max_length=255, null=True, verbose_name='image')),
                ('dog_breed', models.CharField(blank=True, help_text='Breed they purchased', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('age', models.CharField(help_text='e.g., "3 months", "1.5 years"', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('color', models.CharField(help_text='e.g., "Golden", "Black & Tan"', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location', models.CharField(help_text='e.g., "Mumbai, Maharashtra"', max_length=255)),
                ('description', models.TextField(help_text='Health info, temperament, parent details, etc.')),
                ('vaccination_status', models.CharField(blank=True, help_text='e.g., "1st dose done", "Fully vaccinated"', max_length=255)),
                ('is_kci_registered', models.BooleanField(default=False, verbose_name='KCI Registered')),
                ('weight', models.CharField(blank=True, help_text='e.g., "5 kg"', max_length=30)),
                ('microchipped', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', '🟢 Available'), ('reserved', '🟡 Reserved'), ('sold', '🔴 Sold')], default='available', max_length=20)),
                ('sold_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='dogs.breed')),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'db_table': 'dogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the photo for accessibility', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Main display photo')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogs.dog')),
            ],
            options={
                'verbose_name': 'Dog Photo',
                'verbose_name_plural': 'Dog Photos',
                'db_table': 'dog_images',
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['status'], name='dogs_status_b9df3c_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['breed'], name='dogs_breed_i_0473c6_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['-created_at'], name='dogs_created_7de674_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['slug'], name='dogs_slug_4416ad_idx'),
        ),
    ]
